# Generated by Django 4.2.15 on 2026-01-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('question1', models.CharField(max_length=255)),
                ('question2', models.CharField(max_length=255)),
                ('question3', models.CharField(max_length=255)),
                ('question4', models.CharField(max_length=255)),
                ('question5', models.CharField(max_length=255)),
            ],
        ),
    ]
